### ISSUE TITLE
Typo in PDO::purgeOldCodesFromDatabase() in master

### ISSUE THREAD

**Issue by Gribnif** [dapphp/securimage#100]
There is a namespace problem in purgeOldCodesFromDatabase(), in that it refers to `PDO::PARAM_INT` on line 448. This should be `\PDO::PARAM_INT` instead, so that the built-in PHP PDO class gets used.

**Comment by Maescool** [comment]
Fixed in #96

**Comment by dapphp** [comment]
Maescool fixed in #96 - thanks!
