### ISSUE TITLE
Redis setTimeout is deprecated consider changing to expire

### ISSUE THREAD

**Issue by jlchassaing** [dapphp/securimage#110]
Hy,
In the Securimage\StorageAdapter\Redis class
on line :     https://github.com/dapphp/securimage/blob/aabde76d839d75a238970661187f83312c2eeda7/StorageAdapter/Redis.php#L51      

   
the setTimeout method is deprecated. consider changing it to expire

**Comment by dapphp** [comment]
Hey jl,

Thanks for pointing that out. Code in the nextgen branch has been updated to use expires if it is available, otherwise setTimeout will be used in older versions.
