### ISSUE TITLE
www.phpcaptcha.org domain for sale

### ISSUE THREAD

**Issue by mmguero** [dapphp/securimage#115]
I understand the project isn't being actively maintained, but you may wish to consider removing the link to [www.phpcaptcha.org](http://www.phpcaptcha.org/) from the GitHub page as that URL seems to be "for sale" by GoDaddy.

**Comment by dapphp** [comment]
Thank you for pointing this out. The links have been removed in commit 2be13fddff68a72dee2c68196dbce7c8f825bcc1.

**Comment by mmguero** [comment]
No problem. FWIW the link is still visible in the "about" section in the upper-right-hand corner of the github repo.
