### ISSUE TITLE
Pull test script into repository

### ISSUE THREAD

**Issue by ahill-shopatron** [dapphp/securimage#36]
On [the Website](http://www.phpcaptcha.org), you make a [test script](http://www.phpcaptcha.org/downloads/securimage_test.php) available so prospective users can check that securimage will work in their environment. Unfortunately, it does not appear to be anywhere in this repository! This makes it somewhat difficult to offer enhancements.

**Comment by morteryler** [comment]
yes

**Comment by dapphp** [comment]
At this point I do not want to add the test script to the repo by default as not to leave it out in the world in any future installs. While there isn't much harm I'd rather not have the script be present when most may not use it.

For reference, the was the latest version kept by the internet archive can be found at https://web.archive.org/web/20170625003810/https://www.phpcaptcha.org/downloads/securimage_test.php if it becomes unavailable in the future. And noted that the test script isn't completely valid for the nextgen/4.0 branch.

Thank you!
