### ISSUE TITLE
Excise GPL-licensed dependencies

### ISSUE THREAD

**Issue by ahill-shopatron** [dapphp/securimage#38]
It appears that securimage is intended to be mostly unrestricted in its use, considering the use of the BSD 2-Clause license in `LICENSE.txt`, and on the use of "BSD" in the `license` key of `composer.json`.

Unfortunately, the PopForge flash library on which it depends is licensed under GPLv3. The icons from the Humility pack are also licensed under (some version of) GPL. The GPL is, by design, viral; since securimage uses these components, the entire work is must be treated as effectively licensed under the GPL.

This is not immediately obvious, and does not seem desirable in a work nominally released under a permissive license like BSD 2. Finding more compatibly-licensed components seems desirable.

I am not a lawyer, etc.

**Comment by peterdd** [comment]
Someone could write an alternative .swf with ming ( https://github.com/libming/libming) 
It is LGPL.

**Comment by dapphp** [comment]
This has always been valid but with where we are today, I would suggest using 4.0 and HTML5 only audio with MP3, or an alternate audio captcha solution.

Going to close but thank you all for the comments and thoughts in past years.
