### ISSUE TITLE
filter() method not called correctly in degrade()

### ISSUE THREAD

**Issue by rlerdorf** [dapphp/securimage#49]
This doesn't look right:

https://github.com/dapphp/securimage/blob/master/WavFile.php#L1771-L1776

filter() takes an array as the first arg

**Comment by dapphp** [comment]
Hi Rasmus,

Thank you for spotting that and pointing it out.  Error corrected and repo updated.

P.S.  I am honored you read my code and commented.  I can't even begin to thank you for everything you've done.
