### ISSUE TITLE
Warning: open_basedir restriction in effect

### ISSUE THREAD

**Issue by peterdd** [dapphp/securimage#63]
Warning: is_executable(): open_basedir restriction in effect. File(/usr/bin/lame) is not within the allowed path(s): (/***:/***) in /***/vendor/dapphp/securimage/securimage.php on line 1361

securimage 3.6.5

workaround: option 'show_audio_button' => false for getCaptchaHtml

**Comment by morteryler** [comment]
Open /etc/php/php.ini and comment out the basedir option like this:
`;open_basedir = ...`

**Comment by dapphp** [comment]
If you can't avoid open basedir I just pushed a fix. To overcome it, you'll need to configure the lame path and set it to empty string:

```
<?php

Securimage::$lame_binary_path = '';
//...

echo Securimage::getCaptchaHtml($options);
```
