### ISSUE TITLE
passing $_POST['code'] to check() is not always a string

### ISSUE THREAD

**Issue by peterdd** [dapphp/securimage#65]
So either please change the documentation/examples how to use the check() function or do a test within the check function if the parameter is really a string before passing it to validate().

If someone changes in a form input-tag from name="code" to name="code[blabla]", $_POST['code'] is passed as an array by PHP.

And then you get

`Warning: strtolower() expects parameter 1 to be string, array given in /***/dapphp/securimage/securimage.php on line 2358`

(securimage 3.6.5)

**Comment by dapphp** [comment]
Admittedly, the documentation on the site is in need of an update, and the current state of things is to use the examples and code as docs (bad!).  But this does seem like a fair warning.

The phpDoc comments for the `check()` function reads:

```
    /**
     * Checks a given code against the correct value from the session and/or database.
     *
     * @param string $code      The captcha code to check
     * @param string $captchaId The ID of the captcha being checked
     * @param bool   $alwaysDelete True to delete captcha data after a failed guess.
     *   Useful if the form post results in a full page reload and the old captcha
     *   ID is never used again. Not so useful on Ajax forms.  (default false)
     *
     * <code>
     *     $code = $_POST['code'];
     *     $img  = new Securimage();
     *     if ($img->check($code) == true) {
     *         $captcha_valid = true;
     *     } else {
     *         $captcha_valid = false;
     *     }
     * </code>
     *
     * @return bool true if the given code was correct, false if not.
     */
```
Admittedly, the 'string' parameter hint is subtle as well.

I'm not against type checking the $code parameter explicitly to prevent this warning from strtolower.  Would a `trigger_error` to the effect of `The $code parameter passed to Securimage::check() must be a string, $type given` be sufficient in your opinion?

**Comment by Vacman** [comment]
My error log is full of this error:
The $code parameter passed to Securimage::check() must be a string, NULL given in /home/xxxx/public_html/securimage/securimage.php on line 1278

**Comment by AndyJAllen** [comment]
> 
> 
> My error log is full of this error:
> The $code parameter passed to Securimage::check() must be a string, NULL given in /home/xxxx/public_html/securimage/securimage.php on line 1278

Yes I get this too.

**Comment by alimbabazade** [comment]
I solved this problem. The problem is solved when I send the values sent from the form with GET instead of POST and receive them with GET.
