### ISSUE TITLE
Can't load image

### ISSUE THREAD

**Issue by milosb793** [dapphp/securimage#72]
Hello @dapphp !

At first, thank you for amazing and hard work!
I beg for help. I lose so much time to figure out a problem. 
I've used your product for my project. It worked everything perfect at localhost. But when i publish it to a server (nginx), i can't even get loaded image. Sound loads well, but image won't display, and refresh button does not work. 

### There is errors
* Console:
![screenshot from 2017-09-26 17 30 44](https://user-images.githubusercontent.com/5012355/30903574-90e55eca-a36f-11e7-94d9-1e59ed5654e7.png)

* Network tab:
![screenshot from 2017-09-27 10 26 06](https://user-images.githubusercontent.com/5012355/30903592-98fa4c2e-a36f-11e7-9ab9-b574e879a65b.png)

* Error log on server:
![screenshot from 2017-09-27 10 26 21](https://user-images.githubusercontent.com/5012355/30903687-e0913b74-a36f-11e7-9192-b7328f0c21fc.png)

This is how it's looks like in form: 
![screenshot from 2017-09-27 10 34 17](https://user-images.githubusercontent.com/5012355/30903544-6fe406d6-a36f-11e7-8ac5-e127d1a987a9.png)

* Inspect element: 
![screenshot from 2017-09-26 17 30 30](https://user-images.githubusercontent.com/5012355/30903710-f2e224dc-a36f-11e7-9817-cf842fd9e62f.png)

Thank you for you time!

**Comment by dapphp** [comment]
Hi,
Thanks for the detail and screenshots.  Based on the nginx error log you posted, the image doesn't work because it looks like PHP is not configured with any type of gd image support.  At 08:06:03, you can see the error "Call to undefined function imagecreate()" which means PHP has no GD support.

You will need to install the gd library for PHP, and also freetype.

**Comment by milosb793** [comment]
@dapphp  Thank you for fast and detailed answer! I will try this today and left results!

**Comment by milosb793** [comment]
That's exactly what i need to do! Thanks man! 
I did `apt-get install php-gd`, restarted `fpm` and `nginx` and there it's, look that beauty: 

![screenshot from 2017-09-28 18 23 03](https://user-images.githubusercontent.com/5012355/30978194-2018f9f2-a47a-11e7-958c-864931e9bcab.png)

:D

**Comment by dapphp** [comment]
Awesome possum!  Thanks for posting and I'm glad you found Securimage useful :)  let me know if I can answer any other questions or help out.
