### ISSUE TITLE
Securimage integrate OWA Exchange

### ISSUE THREAD

**Issue by wish01** [dapphp/securimage#73]
How intagrate Securimage in OWA Exchange 2013?

**Comment by dapphp** [comment]
I personally have no idea if it's possible.  I don't think so though.  You'd need to install PHP within IIS which is fine, and while you could edit the OWA login templates to display the captcha, I seriously doubt you have the ability to edit the backend code that handles the login (though I could be wrong).  My guess is that the stuff that handles that is proprietary code compiled into DLLs and other things you don't have the ability to change.

I'd suggest posting on a Microsoft forum asking if it would be possible to hook into OWA's login code to run your own code.  If it were possible, you'd then likely be better off using an ASP.NET / C# captcha that would integrate a little easier than PHP.

Feel free to post back if you find anything out.
