### ISSUE TITLE
Multiple forms validate randomly with setNamespace

### ISSUE THREAD

**Issue by linuxoid** [dapphp/securimage#75]
I have multiple forms on a page which seem to validate strangely or randomly. 

1. If I enter the first code correctly, the same form will validate correctly every time until the code is entered incorrectly. After this validation always fails until I click on the image to reload it, then it all starts fine.
2. Regardless of the 1st form processed, any other form fails validation until the image is clicked to reload. Then it start passing as in point 1.

Namespaces don't seem to help.

This is the view.php:
```
echo '<div class="form-group">';
    $captcha->setNamespace($bUID);
    $captcha->display();
    echo $form->text('code'.$bUID, $code);
echo '</div>';

```
This is the controller.php:
```
$captcha->setNamespace($_POST['buid']);
if (!$captcha->check('code')) {
    array_push($this->form_errors, $this->error_code);
}
```
The $bUID is a unique form block number, that is each form field is unique.

Looks like even though each form is unique, the Securimage image is created one for all, not as one for each form. And the namespaces don't help for some reason.

Is there any way to create a captcha image with a unique code and path for each unique form?

**Comment by morteryler** [comment]
Solving the problem is ingeniously and simply updating captcha after clicking on the captcha form input field will help. Thus, the captcha will reboot and become actual and this problem will disappear. There is no other solution now.
