### ISSUE TITLE
first captcha code always wrong

### ISSUE THREAD

**Issue by gstlouisgit** [dapphp/securimage#84]
I have this snippet in a form

```
<div class="col-md-6 form-group" style="margin-bottom: 5px; margin-top: 2em;">
                <a href="#" class="pull-right captcha-link" onclick="document.getElementById('captcha').src = '/assets/securimage/securimage_show.php?' + Math.random(); return false"><img src="/assets/securimage/images/refresh.png" style="width: 30px;"></a>
                  <img id="captcha" src="/assets/securimage/securimage_show.php" alt="CAPTCHA Image">
                  <input type="text" id="captcha_code" class="form-control required" size="10" maxlength="6">
</div>
```

Once the user enteres the characters there is an ajax triggered to a file containing
`<?php
require_once($_SERVER['DOCUMENT_ROOT'] . "/assets/securimage/securimage.php");

if(isset($_POST["captcha_code"])){
	$securimage = new Securimage();
	$result = array();

	if($securimage->check($_POST["captcha_code"]) == false){
	  // the code was incorrect
		$result["succcess"] = false;
		$result["error"] = $_POST["captcha_code"];
		echo json_encode($result);
	}else{
		$result["succcess"] = true;
		$result['data'] = '<input type="hidden" name="cap" value="approved">';
		echo json_encode($result);
	}
	unset($_POST);
}
exit;
?>`

yet every initial time this event is triggered, even if the code is correct I get a return as false.
If I refresh the captcha, then enter the code it works just fine
If I do a js to trigger a click() on the a tag holding the captcha, again it works fine
But that first time on page load, never, even works the first time.

What could I be doing wrong?  I have tried putting session_start() at begining on file and this does nothing.

**Comment by mehmeth86** [comment]
```
$(document).ready(function() {
                    $('#your_html_a_tag_id').trigger('click');
}
```

**Comment by dapphp** [comment]
With ajax forms you need to be careful not to validate the captcha if any other form validation fails. When check() is called with the correct code, it cannot be used again. Sometimes this happens with ajax forms and causes problems. Otherwise, this might be caused by session/database config issues.

For future integrations/updates and to get around this issue, check out the nextgen/4.0 branch.
