### ISSUE TITLE
can't install via composer

### ISSUE THREAD

**Issue by Pappu420** [dapphp/securimage#91]
Hello

I copied composer.json file but can't install via composer

 /usr/bin/composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files

  [RuntimeException]
  Could not scan for classes inside "securimage.php" which does not appear to
   be a file nor a folder

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by ve3** [comment]
Make sure you specified version 3.x not 4

**Comment by dapphp** [comment]
It looks like this will happen if you copy the project's composer.json file to a new directory and run `composer install` without having securimage.php in the directory.

With securimage you don't need to do this, but simply require "dapphp/securimage" in your project's composer.json file.
