### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by peter279k** [dapphp/securimage#99]
It seems that this project is inactive for about two years.

There're many issues are waiting for concerning and pull requests need to be reviewed and merged.

@dapphp, is it possible to add more collaborators to join this repository :)?

**Comment by dapphp** [comment]
This [comment](https://github.com/dapphp/securimage/issues/66#issuecomment-636279862) about sums it up. I will gladly add anyone as a collaborator if they are interested.

**Comment by dregad** [comment]
@dapphp in the light of the above-mentioned comment, I think it would be a good idea to make it more explicit that this project is no longer maintained / abandoned and looking for someone to take it over. I would suggest at least updating the repository's description and adding a note on the README file here on GitHub, as well as the home page at https://www.phpcaptcha.org/.

Anyway, sorry to hear that, and many thanks for the time and efforts you invested into this, securimage has served us well over the years and it is sad to see it go.

**Comment by 8ctopus** [comment]
I recommend to read @dapphp 's post https://github.com/dapphp/securimage/issues/66#issuecomment-636279862

**Comment by Neustradamus** [comment]
To follow.

**Comment by Neustradamus** [comment]
It is a little alive...

**Comment by peter279k** [comment]
Closed because it's alive...

**Comment by Neustradamus** [comment]
@peter279k: I have requested a new build:
- https://github.com/dapphp/securimage/issues/117
